# Generated by Django 6.0.4 on 2026-05-05 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaComprension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Comprensión del Capítulo 1', max_length=200, verbose_name='Título de la prueba')),
                ('pregunta', models.TextField(verbose_name='Pregunta')),
                ('opcion_a', models.CharField(max_length=500, verbose_name='Opción A')),
                ('opcion_b', models.CharField(max_length=500, verbose_name='Opción B')),
                ('opcion_c', models.CharField(blank=True, max_length=500, verbose_name='Opción C (opcional)')),
                ('opcion_d', models.CharField(blank=True, max_length=500, verbose_name='Opción D (opcional)')),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Respuesta correcta')),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='media', max_length=10, verbose_name='Dificultad')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_comprension', to='libros.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Prueba de comprensión',
                'verbose_name_plural': 'Pruebas de comprensión',
                'ordering': ['libro', 'dificultad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntentoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Respuesta del usuario')),
                ('correcta', models.BooleanField(verbose_name='¿Correcta?')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del intento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_pruebas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='comprension.pruebacomprension', verbose_name='Prueba')),
            ],
            options={
                'verbose_name': 'Intento de prueba',
                'verbose_name_plural': 'Intentos de pruebas',
                'ordering': ['-fecha_intento'],
            },
        ),
    ]
