# Generated by Django 6.0.4 on 2026-05-05 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de la sesión')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la sesión')),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, help_text='Calculado automáticamente al finalizar', null=True, verbose_name='Duración (segundos)')),
                ('paginas_leidas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Páginas leídas')),
                ('palabras_por_pagina', models.PositiveIntegerField(default=250, help_text='Se usa para calcular palabras por minuto', verbose_name='Palabras por página')),
                ('palabras_por_minuto', models.PositiveIntegerField(blank=True, help_text='Calculado automáticamente al finalizar', null=True, verbose_name='Palabras por minuto (PPM)')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Sesión activa?')),
                ('notas', models.TextField(blank=True, help_text='Apuntes sobre esta sesión de lectura', verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_lectura', to='libros.libro', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_lectura', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de lectura',
                'verbose_name_plural': 'Sesiones de lectura',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_actual', models.PositiveIntegerField(default=0, verbose_name='Página actual')),
                ('paginas_totales', models.PositiveIntegerField(blank=True, help_text='Opcional, se usa para calcular el % de progreso', null=True, verbose_name='Total de páginas')),
                ('completado', models.BooleanField(default=False, verbose_name='¿Completado?')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, help_text='Evaluación personal del libro', null=True, verbose_name='Calificación (1-5)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='libros.libro', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_libros', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de libro',
                'verbose_name_plural': 'Progresos de libros',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('usuario', 'libro')},
            },
        ),
    ]
