# Generated by Django 6.0.4 on 2026-05-06 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.CharField(default='Español', max_length=50, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de portada'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True, verbose_name='Fecha de préstamo')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('estado', models.CharField(choices=[('active', 'Activo'), ('overdue', 'Vencido'), ('returned', 'Devuelto')], default='active', max_length=10, verbose_name='Estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='libros.libro', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='libros.libro', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'libro')},
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(verbose_name='Calificación (1-5)')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('marcada', models.BooleanField(default=False, verbose_name='Marcada para moderación')),
                ('razon_marca', models.CharField(blank=True, default='', max_length=200, verbose_name='Razón de la marca')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='libros.libro', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha'],
                'unique_together': {('libro', 'usuario')},
            },
        ),
    ]
