# Generated by Django 6.0.4 on 2026-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Archivo PDF'),
        ),
        migrations.AddField(
            model_name='libro',
            name='pdf_source_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL de origen del PDF'),
        ),
    ]
