# Generated by Django 6.0.4 on 2026-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('user', 'Usuario'), ('librarian', 'Bibliotecario'), ('admin', 'Administrador')], default='user', max_length=10, verbose_name='Rol'),
        ),
    ]
