# Generated by Django 6.0.4 on 2026-05-05 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del logro')),
                ('descripcion', models.TextField(help_text='¿Qué debe hacer el usuario para obtenerlo?', verbose_name='Descripción')),
                ('icono', models.CharField(default='🏆', help_text='Emoji que representa el logro, ej: 📖 ⚡ 🔥', max_length=50, verbose_name='Icono (emoji)')),
                ('categoria', models.CharField(choices=[('sesiones', 'Sesiones'), ('paginas', 'Páginas'), ('tiempo', 'Tiempo de lectura'), ('velocidad', 'Velocidad'), ('racha', 'Rachas'), ('libros', 'Libros completados'), ('especial', 'Especial')], default='sesiones', max_length=20, verbose_name='Categoría')),
                ('tipo_requisito', models.CharField(choices=[('sesiones', 'Nº de sesiones'), ('paginas', 'Páginas leídas'), ('tiempo_minutos', 'Minutos de lectura'), ('ppm', 'Palabras por minuto (PPM)'), ('racha_dias', 'Días de racha'), ('libros_completados', 'Libros completados'), ('calificaciones', 'Libros calificados')], help_text='Qué estadística debe alcanzar', max_length=25, verbose_name='Tipo de requisito')),
                ('requisito_valor', models.PositiveIntegerField(help_text='Cantidad necesaria para desbloquear el logro', verbose_name='Valor del requisito')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar los logros en la lista', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de desbloqueo')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gamificacion.logro', verbose_name='Logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Logro de usuario',
                'verbose_name_plural': 'Logros de usuarios',
                'ordering': ['-fecha_desbloqueo'],
                'unique_together': {('usuario', 'logro')},
            },
        ),
    ]
