# Generated by Django 6.0.4 on 2026-05-05 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: "Leer 20 páginas al día"', max_length=200, verbose_name='Nombre de la meta')),
                ('tipo', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10, verbose_name='Periodicidad')),
                ('tipo_objetivo', models.CharField(choices=[('paginas', 'Páginas'), ('minutos', 'Minutos'), ('sesiones', 'Sesiones')], max_length=10, verbose_name='Tipo de objetivo')),
                ('objetivo_valor', models.PositiveIntegerField(help_text='Cantidad a alcanzar (ej: 20 páginas, 30 minutos, 3 sesiones)', verbose_name='Valor del objetivo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_lectura', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Meta de lectura',
                'verbose_name_plural': 'Metas de lectura',
                'ordering': ['-activa', 'tipo', 'fecha_creacion'],
            },
        ),
    ]
